insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'EUR', 'BUY', 0.00322);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'CHF', 'BUY', 0.00384);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'USD', 'BUY', 0.00383);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'GBP', 'BUY', 0.00284);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'EUR', 'SELL', 0.00314);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'CHF', 'SELL', 0.00376);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'USD', 'SELL', 0.00375);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'HUF', 'GBP', 'SELL', 0.00276);

insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'HUF', 'BUY', 314.479);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'CHF', 'BUY', 1.19467);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'USD', 'BUY', 1.19242);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'GBP', 'BUY', 0.88143);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'HUF', 'SELL', 314.471);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'CHF', 'SELL', 1.19459);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'USD', 'SELL', 1.19234);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'EUR', 'GBP', 'SELL', 0.88135);

insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'HUF', 'BUY', 263.228);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'EUR', 'BUY', 0.83712);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'USD', 'BUY', 0.99800);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'GBP', 'BUY', 0.73771);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'HUF', 'SELL', 263.220);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'EUR', 'SELL', 0.83704);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'USD', 'SELL', 0.99792);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'CHF', 'GBP', 'SELL', 0.73763);

insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'HUF', 'BUY', 263.772);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'EUR', 'BUY', 0.83870);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'CHF', 'BUY', 1.00209);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'GBP', 'BUY', 0.73897);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'HUF', 'SELL', 263.764);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'EUR', 'SELL', 0.83862);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'CHF', 'SELL', 1.00201);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'USD', 'GBP', 'SELL', 0.73889);

insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'HUF', 'BUY', 356.831);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'EUR', 'BUY', 1.13457);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'CHF', 'BUY', 1.35566);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'USD', 'BUY', 1.35317);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'HUF', 'SELL', 356.823);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'EUR', 'SELL', 1.13449);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'CHF', 'SELL', 1.35558);
insert into EXCHANGE_RATE (ID, FROM_CURRENCY, TO_CURRENCY, TYPE, RATE) values (SEQ_EXCHANGE_RATE.nextval, 'GBP', 'USD', 'SELL', 1.35309);
